### PR TITLE
Develop version 1.1.0

### PR DESCRIPTION
**Pull request by balazskreith**
* Add MediasoupProducerCollector for Mediasop Producer objects 
  * Add MediasoupConsumerCollector for Mediasoup Consumer objects 
  * Add MediasoupDataConsumerCollector for Mediasoup DataConsumer objects 
  * Add MediasoupDataProducerCollector for Mediasoup DataProducer objects
  * Add MediasoupTransportCollector for Mediasoup Transport objects
  * Add MediasoupRouterCollector for Mediasoup Router objects
  * Add MediasoupWorkerCollector for Mediasoup Worker objects
  * Add CustomSfuEvent from schema 2.2.0 * Add Collector as an object
  * Move Mediasoup to monitor level and make MediasoupMonitor as an implementation of SfuMonitor
  * PromiseFetcher bugfix if the min and max pacing are the same

### CODE REVIEW

**Comment by havfo** [comment]
https://github.com/ObserveRTC/sfu-monitor-js/blob/67e21bfc239b5baf9aae7c8e281c99ecbfc5f56a/src/SfuMonitorImpl.ts#L139

This method, and

https://github.com/ObserveRTC/sfu-monitor-js/blob/67e21bfc239b5baf9aae7c8e281c99ecbfc5f56a/src/SfuMonitorImpl.ts#L147

are not async, no?

**Comment by havfo** [comment]
It makes sense to run these in parallel?
https://github.com/ObserveRTC/sfu-monitor-js/blob/67e21bfc239b5baf9aae7c8e281c99ecbfc5f56a/src/mediasoup/MediasoupCollector.ts#L205

**Comment by havfo** [comment]
These also in parallel?

https://github.com/ObserveRTC/sfu-monitor-js/blob/67e21bfc239b5baf9aae7c8e281c99ecbfc5f56a/src/mediasoup/MediasoupCollector.ts#L512

**Comment by balazskreith** [comment]
> https://github.com/ObserveRTC/sfu-monitor-js/blob/67e21bfc239b5baf9aae7c8e281c99ecbfc5f56a/src/SfuMonitorImpl.ts#L139
> 
> This method, and
> 
> https://github.com/ObserveRTC/sfu-monitor-js/blob/67e21bfc239b5baf9aae7c8e281c99ecbfc5f56a/src/SfuMonitorImpl.ts#L147
> 
> are not async, no?

sending is async to give a possibility for implementation using async function and await. for instance a custom Websocket Transport is implemented which only considers a sample sent if it got an application level acknowledgment. In that case await send() means it got it. Maybe it is a stupid idea to implement a transport like this but maybe not. 
Conceptually, I think sending a letter via a post office is an async operation and if you wait in front of the post office for the note that it Is sent its your (so the invoker) business.

Sampling can be sync, and maybe makes more sense as it does not require any async operation and it will always kept inside the SfuMonitor and Sampler, so yeah...

**Comment by balazskreith** [comment]
> It makes sense to run these in parallel?
> 
> https://github.com/ObserveRTC/sfu-monitor-js/blob/67e21bfc239b5baf9aae7c8e281c99ecbfc5f56a/src/mediasoup/MediasoupCollector.ts#L205

MediasoupCollector is deprecated and will be removed from this PR. 
MediasoupCollector is one StatsCollector for all mediasoup object. It is splitted in a way that now each Producer, DataConsumer, DataProducer Consumer, and Transport has a dedicated StatsCollector and they are all polled parallel (but PromiseFetcher controls the one time fetched async operations).

**Pull request merged**
